name: GitFetch

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: echo test
        run: echo "testing from main"
      - uses: actions/checkout@v2
      - name: updating Readme
        run: |
         echo README.md
         echo "testing" >> README.md
         git config --global user.email "you@example.com"
         git config --global user.name "Your Name"
         git add .
         git commit -m "update readme"
         git push origin
